name: galleria P7
favicon: null
layout_spectrum: 0.18254475039429963
typography_spectrum: 0.5783304581418633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6666170789394528
  rhythmicContrast: 0.24092116276733577
purpose: []
